### ISSUE TITLE
Validation issue on subdomain instances

### ISSUE THREAD

**Issue by dredshep** [driccio98/kbin-link#1]
red:

![](https://sh.itjust.works/pictrs/image/e64c21c1-2b32-4d16-8587-b1bf95a6e34c.png)

normal:

![](https://sh.itjust.works/pictrs/image/061f7df6-c35a-4ee4-965c-82c72a78e5d3.png)

I think it wants it to only have one `.` because of some regex site validation.

**Comment by daniel-lxs** [comment]
Fixed with [c050f1b](https://github.com/driccio98/kbin-link/commit/c050f1becfc45d762b1a76b20ef79d0907ad6a41) however this extension only works with kbin due to the structure of the links, if you want to use it for Lemmy you should use https://github.com/FackJox/lemmy-link
Edit: You can now user it for lemmy too
